---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test1-chatbot-aug7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test1-chatbot-aug7 
  name: test1-chatbot-aug7
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi